sonar.projectKey=com.sap.btp.zcurdapp.zopa
sonar.projectName=Gowtham OPA5 Tests
sonar.projectVersion=0.0.1
sonar.sources=webapp
sonar.exclusions=webapp/resources/**,webapp/test/**,webapp/localService/**,dist/**,node_modules/**
sonar.tests=webapp/test
sonar.test.inclusions=webapp/test/**/*.js
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info
sonar.testExecutionReportPaths=reports/TESTS-karma.xml
sonar.sourceEncoding=UTF-8