sonar.projectKey=com.sap.btp.zcurdapp.zopa
sonar.projectName=Gowtham OPA5 Tests
sonar.projectVersion=0.0.1
sonar.host.url=http://54.144.105.219:9000
sonar.token=squ_79729918fc50c1b6031ee56a075dc51b247406ce
sonar.login=squ_79729918fc50c1b6031ee56a075dc51b247406ce
sonar.sources=webapp
sonar.exclusions=webapp/resources/**,webapp/localService/**,webapp/test/**,dist/**,node_modules/**,reports/**
sonar.tests=webapp/test
sonar.test.inclusions=webapp/test/**/*.js
sonar.javascript.file.suffixes=.js
sonar.testExecutionReportPaths=reports/test-execution.xml
sonar.sourceEncoding=UTF-8